//TODO: когда будет больше времени, добавлю генераторы экшкнов.
export const ADD_CONSTRUCTOR_ITEM = "ADD_CONSTRUCTOR_ITEM";
export const REMOVE_CONSTRUCTOR_ITEM = "REMOVE_CONSTRUCTOR_ITEM";

export const SET_DRAG = "SET_DRAG";

export const CREATE_EMPTY_ITEM = "CREATE_EMPTY_ITEM";
export const SET_EMPTY_ITEM = "SET_EMPTY_ITEM";
export const CLEAR_INDEX_EMPTY_ITEM = "CLEAR_INDEX_EMPTY_ITEM";

export const SAVE_START_DRAG_POSITION = "CREATE_START_DRAG_POSITION";
export const CLEAR_START_DRAG_POSITION = "CLEAR_START_DRAG_POSITION";

export const CLEAR_BURGER_CONSTRUCTOR = "CLEAR_BURGER_CONSTRUCTOR";